CREATE TABLE IF NOT EXISTS games (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    description TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS event_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    event_date TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS game_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id INTEGER NOT NULL,
    day_id INTEGER NOT NULL,
    capacity INTEGER NOT NULL CHECK(capacity > 0),
    start_time TEXT,
    end_time TEXT,
    UNIQUE(game_id, day_id),
    FOREIGN KEY(game_id) REFERENCES games(id) ON DELETE CASCADE,
    FOREIGN KEY(day_id) REFERENCES event_days(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS registrations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_day_id INTEGER NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    cancel_token TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(game_day_id) REFERENCES game_days(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_registrations_game_day ON registrations(game_day_id);
CREATE INDEX IF NOT EXISTS idx_registrations_person ON registrations(first_name, last_name, class_name);
